services:
  esp:
    build: .
    command: /bin/bash
    depends_on:
      - xilinx
    environment:
      - DISPLAY
    image: esp:2024.1.0
    network_mode: host
    ports:
      - "127.0.0.1:3121-3122:3121-3122"
    privileged: true
    volumes:
      - ./env:/home/espuser/env
      - ./esp/.cache:/home/espuser/esp.cache
      - ./esp/accelerators/rtl/espacc_rtl:/home/espuser/esp/accelerators/rtl/espacc_rtl
      - ./esp/accelerators/hls4ml/iris_hls4ml:/home/espuser/esp/accelerators/hls4ml/iris_hls4ml
      - ./esp/accelerators/vivado_hls/ldpc_vivado:/home/espuser/esp/accelerators/vivado_hls/ldpc_vivado
      - ./esp/socs/fft-soc:/home/espuser/esp/socs/fft-soc
      - ./esp/socs/iris-soc:/home/espuser/esp/socs/iris-soc
      - ./esp/socs/ldpc-soc:/home/espuser/esp/socs/ldpc-soc
      - ./esp/tech:/home/espuser/esp/tech
      - ./work:/home/espuser/work
      - xilinx:/tools

  xilinx:
    image: xilinx:20.04_2023.2
    restart: always
    volumes:
      - xilinx:/tools

volumes:
  xilinx: {}
