services:
  esp:
    build: .
    command: /bin/bash
    depends_on:
      - xilinx
    environment:
      - DISPLAY
    image: esp:2023.1.0
    network_mode: host
    ports:
      - "127.0.0.1:3121-3122:3121-3122"
    privileged: true
    volumes:
      - ./env:/home/espuser/env
      - ./esp/accelerators/rtl/espacc_rtl:/home/espuser/esp/accelerators/rtl/espacc_rtl
      - ./esp/accelerators/hls4ml/iris_hls4ml:/home/espuser/esp/accelerators/hls4ml/iris_hls4ml
      - ./esp/accelerators/rtl/rng_rtl:/home/espuser/esp/accelerators/rtl/rng_rtl
      - ./esp/accelerators/vivado_hls/ldpc_vivado:/home/espuser/esp/accelerators/vivado_hls/ldpc_vivado
      - ./esp/socs/iris-soc:/home/espuser/esp/socs/iris-soc
      - ./esp/socs/ldpc-soc:/home/espuser/esp/socs/ldpc-soc
      - ./work:/home/espuser/work
      - xilinx:/tools

  xilinx:
    image: xilinx:18.04_2019.2
    volumes:
      - xilinx:/tools

volumes:
  xilinx: {}
