# Docker container for ESP use
# Copyright 2023 Carnegie Mellon University.
# MIT (SEI)
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
# This material is based upon work funded and supported by the Department of
# Defense under Contract No. FA8702-15-D-0002 with Carnegie Mellon University
# for the operation of the Software Engineering Institute, a federally funded
# research and development center.
# The view, opinions, and/or findings contained in this material are those of
# the author(s) and should not be construed as an official Government position,
# policy, or decision, unless designated by other documentation.
# NO WARRANTY. THIS CARNEGIE MELLON UNIVERSITY AND SOFTWARE ENGINEERING
# INSTITUTE MATERIAL IS FURNISHED ON AN "AS-IS" BASIS. CARNEGIE MELLON
# UNIVERSITY MAKES NO WARRANTIES OF ANY KIND, EITHER EXPRESSED OR IMPLIED,
# AS TO ANY MATTER INCLUDING, BUT NOT LIMITED TO, WARRANTY OF FITNESS FOR
# PURPOSE OR MERCHANTABILITY, EXCLUSIVITY, OR RESULTS OBTAINED FROM USE OF THE
# MATERIAL. CARNEGIE MELLON UNIVERSITY DOES NOT MAKE ANY WARRANTY OF ANY KIND
# WITH RESPECT TO FREEDOM FROM PATENT, TRADEMARK, OR COPYRIGHT INFRINGEMENT.
# [DISTRIBUTION STATEMENT A] This material has been approved for public release
# and unlimited distribution.  Please see Copyright notice for non-US
# Government use and distribution.
# DM23-0186

# Cadence: Stratus HLS, Incisive, XCelium
CDS_PATH=/afs/ece.cmu.edu/support/cds/share/image/usr/cds
STRATUS_PATH=${CDS_PATH}/stratus-18.20.100
INCISIVE_PATH=${CDS_PATH}/incisiv-15.20.006
XCELIUM_PATH=${CDS_PATH}/xcelium-22.03
export BDW_INCISIVE_HOME=${XCELIUM_PATH}
export LM_LICENSE_FILE=${CDS_PATH}/share/license/license.dat
export PATH=$PATH:${STRATUS_PATH}/bin:${INCISIVE_PATH}/tools/cdsgcc/gcc/bin:${XCELIUM_PATH}/tools/cdsgcc/gcc/bin
export CDS_AUTO_64BIT=all
# export HOST=$(hostname) # for Ubuntu only

export XILINX_PATH=/afs/ece.cmu.edu/support/xilinx
export VIVADO_PATH=${XILINX_PATH}/xilinx/share/image/usr/local/xilinx/Vivado-2019.2/Vivado/2019.2
export XILINXD_LICENSE_FILE=2101@xilinx-lic.ece.local.cmu.edu
. ${VIVADO_PATH}/settings64.sh

export RISCV=/home/espuser/riscv
export PATH=${RISCV}/bin:${PATH}
export ESP_ROOT=/home/espuser/esp

# for doing csim
export LIBRARY_PATH=/usr/lib/x86_64-linux-gnu

echo "Setting up X forwarding"
XAUTH=/home/espuser/env/.Xauthority
if test -f "$XAUTH"; then
    echo "Setting XAUTHORITY to $XAUTH"
    export XAUTHORITY=$XAUTH
else
    echo "File $XAUTH not found. Skipping X forwarding."
fi
