export XILINXD_LICENSE_FILE=/home/espuser/env/Xilinx.lic
export VIVADO_PATH=/tools/Xilinx/Vivado/2023.2
. ${VIVADO_PATH}/settings64.sh
export RISCV=/home/espuser/riscv
export PATH=${RISCV}/bin:${PATH}
export ESP_ROOT=/home/espuser/esp

# for doing csim
export LIBRARY_PATH=/usr/lib/x86_64-linux-gnu

umask 002

echo "Setting up X forwarding"
XAUTH=/home/espuser/env/.Xauthority
if test -f "$XAUTH"; then
    echo "Setting XAUTHORITY to $XAUTH"
    export XAUTHORITY=$XAUTH
else
    echo "File $XAUTH not found. Skipping X forwarding."
fi
