export XAUTHORITY=/home/espuser/env/.Xauthority
export XILINXD_LICENSE_FILE=/home/espuser/Xilinx.lic
export VIVADO_PATH=/tools/Xilinx/Vivado/2019.2
. ${VIVADO_PATH}/settings64.sh
export RISCV=/home/espuser/esp/riscv
export PATH=${RISCV}/bin:${PATH}
export ESP_ROOT=/home/espuser/esp

echo "Setting up X forwarding"
XAUTH=/home/espuser/env/.Xauthority
if test -f "$XAUTH"; then
    echo "Setting XAUTHORITY to $XAUTH"
    export XAUTHORITY=$XAUTH
else
    echo "File $XAUTH not found. Skipping X forwarding."
fi
